// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7GAPB9CEuifXKPwC7_vOfQHU1r5f8wY',
    appId: '1:563705822511:web:14f8e24330a44ac58b75da',
    messagingSenderId: '563705822511',
    projectId: 'official-agreement',
    authDomain: 'official-agreement.firebaseapp.com',
    storageBucket: 'official-agreement.firebasestorage.app',
    measurementId: 'G-CB0N09JLHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2W9IeJQuhAmLfb2RdKJWh0aAreqR2YI',
    appId: '1:563705822511:android:b7f8d0cad817f7ac8b75da',
    messagingSenderId: '563705822511',
    projectId: 'official-agreement',
    storageBucket: 'official-agreement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKXY_p-TFXW5VlIVeq7hGDs1Er4odkUD8',
    appId: '1:563705822511:ios:80be0be3e796179a8b75da',
    messagingSenderId: '563705822511',
    projectId: 'official-agreement',
    storageBucket: 'official-agreement.firebasestorage.app',
    iosClientId: '563705822511-e2gphrp8msnm2d90l9msstg8kh1kij3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.officialagreement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKXY_p-TFXW5VlIVeq7hGDs1Er4odkUD8',
    appId: '1:563705822511:ios:80be0be3e796179a8b75da',
    messagingSenderId: '563705822511',
    projectId: 'official-agreement',
    storageBucket: 'official-agreement.firebasestorage.app',
    iosClientId: '563705822511-e2gphrp8msnm2d90l9msstg8kh1kij3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.officialagreement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7GAPB9CEuifXKPwC7_vOfQHU1r5f8wY',
    appId: '1:563705822511:web:b0a3e577365c31578b75da',
    messagingSenderId: '563705822511',
    projectId: 'official-agreement',
    authDomain: 'official-agreement.firebaseapp.com',
    storageBucket: 'official-agreement.firebasestorage.app',
    measurementId: 'G-7E70XDS0BN',
  );
}
